"""Bilibili video subtitle extractor."""

import logging
import re

from bilibili_api import video, Credential

from app.tools.extractors.base import (
    ContentExtractor,
    ExtractionError,
    ExtractionResult,
    RawContentChunk,
)
from app.tools.extractors.utils import group_segments

logger = logging.getLogger(__name__)


class BilibiliExtractor(ContentExtractor):
    """Extract subtitles from Bilibili videos.

    Subtitle priority:
    1. CC subtitles (human-uploaded, highest quality)
    2. AI-generated subtitles (auto-generated by Bilibili)
    3. No subtitles → raise ExtractionError with guidance

    Cookie auth is optional but recommended — some videos restrict
    subtitle access to logged-in users.
    """

    def __init__(self, credential: Credential | None = None,
                 whisper_mode: str = "api", whisper_model: str = "base"):
        """Initialize with optional Bilibili credential.

        Args:
            credential: bilibili_api.Credential for authenticated access.
                Created from SESSDATA + bili_jct + buvid3 cookies.
                If None, only publicly accessible subtitles work.
            whisper_mode: Whisper ASR mode ("api" or "local").
            whisper_model: Whisper model name for local mode.
        """
        self.credential = credential
        self._whisper_mode = whisper_mode
        self._whisper_model = whisper_model

    def supported_source_type(self) -> str:
        return "bilibili"

    async def extract(self, source: str, **kwargs) -> ExtractionResult:
        """Extract subtitles from a Bilibili video URL.

        Args:
            source: Bilibili URL (e.g. "https://www.bilibili.com/video/BV1xx...")
            **kwargs:
                page: int — for multi-part videos, which part (default 0 = first)

        Returns:
            ExtractionResult with subtitle chunks.
        """
        bvid = self._parse_bvid(source)
        page = kwargs.get("page", 0)

        v = video.Video(bvid=bvid, credential=self.credential)

        # 1. Get video info (title, duration, pages)
        info = await v.get_info()
        title = info["title"]
        duration = info.get("duration", 0)
        pages = info.get("pages", [])

        # Validate page index
        if page >= len(pages) and len(pages) > 0:
            raise ExtractionError(
                f"Page {page} not found. Video has {len(pages)} pages.",
                source_type="bilibili",
                details={"bvid": bvid, "page_count": len(pages)},
            )

        cid = pages[page]["cid"] if pages else info.get("cid")

        # 2. Get subtitle list
        subtitle_info = await v.get_subtitle(cid=cid)
        subtitles = subtitle_info.get("subtitles", [])

        media_url = f"https://www.bilibili.com/video/{bvid}"

        if not subtitles:
            logger.info(f"No subtitles for {bvid}, falling back to Whisper ASR")
            from app.tools.extractors.asr import WhisperService
            whisper = WhisperService(mode=self._whisper_mode, model=self._whisper_model)
            segments = await whisper.transcribe(source)
            subtitle_source = "whisper"
            chunks = group_segments(
                segments=segments, source_type="bilibili",
                media_url=media_url, window_seconds=60,
            )
        else:
            # 3. Pick best subtitle (prefer CC over AI-generated)
            best_subtitle = self._pick_best_subtitle(subtitles)

            # 4. Fetch subtitle content (JSON with timestamp segments)
            subtitle_url = best_subtitle["subtitle_url"]
            if subtitle_url.startswith("//"):
                subtitle_url = "https:" + subtitle_url

            import httpx
            async with httpx.AsyncClient() as client:
                resp = await client.get(subtitle_url)
                resp.raise_for_status()
                subtitle_data = resp.json()

            subtitle_source = best_subtitle.get("lan", "unknown")
            chunks = group_segments(
                segments=subtitle_data.get("body", []),
                source_type="bilibili",
                media_url=media_url, window_seconds=60,
            )

        return ExtractionResult(
            title=title,
            chunks=chunks,
            metadata={
                "platform": "bilibili",
                "video_id": bvid,
                "bvid": bvid,
                "cid": cid,
                "title": title,
                "author": info.get("owner", {}).get("name", ""),
                "duration": duration,
                "subtitle_source": subtitle_source,
                "media_url": media_url,
                "page": page,
                "page_count": len(pages),
            },
        )

    @staticmethod
    def _parse_bvid(url: str) -> str:
        """Extract BV号 from various Bilibili URL formats.

        Supports:
        - https://www.bilibili.com/video/BV1xx411c7XW
        - https://b23.tv/BV1xx411c7XW
        - https://www.bilibili.com/video/BV1xx411c7XW?p=2
        - BV1xx411c7XW (raw BV号)
        """
        # Direct BV号
        if re.match(r"^BV[\w]+$", url):
            return url

        # URL patterns
        match = re.search(r"(BV[\w]+)", url)
        if match:
            return match.group(1)

        raise ExtractionError(
            f"Cannot parse BV号 from URL: {url}",
            source_type="bilibili",
            details={"url": url},
        )

    @staticmethod
    def _pick_best_subtitle(subtitles: list[dict]) -> dict:
        """Pick the best subtitle track.

        Priority: CC zh-CN > CC zh > AI zh > any CC > any AI > first available
        """
        cc_subs = [s for s in subtitles if not s.get("lan", "").startswith("ai-")]
        ai_subs = [s for s in subtitles if s.get("lan", "").startswith("ai-")]

        # Prefer Chinese CC
        for sub in cc_subs:
            if sub.get("lan") in ("zh-CN", "zh-Hans"):
                return sub
        for sub in cc_subs:
            if "zh" in sub.get("lan", ""):
                return sub

        # Then Chinese AI
        for sub in ai_subs:
            if "zh" in sub.get("lan", ""):
                return sub

        # Fallback
        return cc_subs[0] if cc_subs else ai_subs[0] if ai_subs else subtitles[0]

