"""Bilibili video subtitle extractor."""

import re

from bilibili_api import video, Credential

from app.tools.extractors.base import (
    ContentExtractor,
    ExtractionError,
    ExtractionResult,
    RawContentChunk,
)


class BilibiliExtractor(ContentExtractor):
    """Extract subtitles from Bilibili videos.

    Subtitle priority:
    1. CC subtitles (human-uploaded, highest quality)
    2. AI-generated subtitles (auto-generated by Bilibili)
    3. No subtitles → raise ExtractionError with guidance

    Cookie auth is optional but recommended — some videos restrict
    subtitle access to logged-in users.
    """

    def __init__(self, credential: Credential | None = None):
        """Initialize with optional Bilibili credential.

        Args:
            credential: bilibili_api.Credential for authenticated access.
                Created from SESSDATA + bili_jct + buvid3 cookies.
                If None, only publicly accessible subtitles work.
        """
        self.credential = credential

    def supported_source_type(self) -> str:
        return "bilibili"

    async def extract(self, source: str, **kwargs) -> ExtractionResult:
        """Extract subtitles from a Bilibili video URL.

        Args:
            source: Bilibili URL (e.g. "https://www.bilibili.com/video/BV1xx...")
            **kwargs:
                page: int — for multi-part videos, which part (default 0 = first)

        Returns:
            ExtractionResult with subtitle chunks.
        """
        bvid = self._parse_bvid(source)
        page = kwargs.get("page", 0)

        v = video.Video(bvid=bvid, credential=self.credential)

        # 1. Get video info (title, duration, pages)
        info = await v.get_info()
        title = info["title"]
        duration = info.get("duration", 0)
        pages = info.get("pages", [])

        # Validate page index
        if page >= len(pages) and len(pages) > 0:
            raise ExtractionError(
                f"Page {page} not found. Video has {len(pages)} pages.",
                source_type="bilibili",
                details={"bvid": bvid, "page_count": len(pages)},
            )

        cid = pages[page]["cid"] if pages else info.get("cid")

        # 2. Get subtitle list
        subtitle_info = await v.get_subtitle(cid=cid)
        subtitles = subtitle_info.get("subtitles", [])

        if not subtitles:
            raise ExtractionError(
                "No subtitles available for this video. "
                "Try a video with CC or AI-generated subtitles.",
                source_type="bilibili",
                details={"bvid": bvid, "has_subtitle": False},
            )

        # 3. Pick best subtitle (prefer CC over AI-generated)
        best_subtitle = self._pick_best_subtitle(subtitles)

        # 4. Fetch subtitle content (JSON with timestamp segments)
        subtitle_url = best_subtitle["subtitle_url"]
        if subtitle_url.startswith("//"):
            subtitle_url = "https:" + subtitle_url

        import httpx
        async with httpx.AsyncClient() as client:
            resp = await client.get(subtitle_url)
            resp.raise_for_status()
            subtitle_data = resp.json()

        # 5. Convert to RawContentChunks
        chunks = self._group_subtitle_segments(
            segments=subtitle_data.get("body", []),
            source_type="bilibili",
            bvid=bvid,
            window_seconds=60,
        )

        media_url = f"https://www.bilibili.com/video/{bvid}"

        return ExtractionResult(
            title=title,
            chunks=chunks,
            metadata={
                "bvid": bvid,
                "cid": cid,
                "duration": duration,
                "uploader": info.get("owner", {}).get("name", ""),
                "page": page,
                "page_count": len(pages),
                "subtitle_type": best_subtitle.get("lan", "unknown"),
                "media_url": media_url,
            },
        )

    @staticmethod
    def _parse_bvid(url: str) -> str:
        """Extract BV号 from various Bilibili URL formats.

        Supports:
        - https://www.bilibili.com/video/BV1xx411c7XW
        - https://b23.tv/BV1xx411c7XW
        - https://www.bilibili.com/video/BV1xx411c7XW?p=2
        - BV1xx411c7XW (raw BV号)
        """
        # Direct BV号
        if re.match(r"^BV[\w]+$", url):
            return url

        # URL patterns
        match = re.search(r"(BV[\w]+)", url)
        if match:
            return match.group(1)

        raise ExtractionError(
            f"Cannot parse BV号 from URL: {url}",
            source_type="bilibili",
            details={"url": url},
        )

    @staticmethod
    def _pick_best_subtitle(subtitles: list[dict]) -> dict:
        """Pick the best subtitle track.

        Priority: CC zh-CN > CC zh > AI zh > any CC > any AI > first available
        """
        cc_subs = [s for s in subtitles if not s.get("lan", "").startswith("ai-")]
        ai_subs = [s for s in subtitles if s.get("lan", "").startswith("ai-")]

        # Prefer Chinese CC
        for sub in cc_subs:
            if sub.get("lan") in ("zh-CN", "zh-Hans"):
                return sub
        for sub in cc_subs:
            if "zh" in sub.get("lan", ""):
                return sub

        # Then Chinese AI
        for sub in ai_subs:
            if "zh" in sub.get("lan", ""):
                return sub

        # Fallback
        return cc_subs[0] if cc_subs else ai_subs[0] if ai_subs else subtitles[0]

    @staticmethod
    def _group_subtitle_segments(
        segments: list[dict],
        source_type: str,
        bvid: str,
        window_seconds: int = 60,
    ) -> list[RawContentChunk]:
        """Group subtitle segments into time-windowed chunks.

        Each Bilibili subtitle segment is typically 2-5 seconds.
        We group them into ~60-second windows to create meaningful chunks
        for LLM analysis.

        Args:
            segments: List of {"from": float, "to": float, "content": str}
            source_type: "bilibili"
            bvid: Video BV号 for media_url
            window_seconds: Target window size in seconds (default 60)

        Returns:
            List of RawContentChunk, each covering ~window_seconds of video.
        """
        if not segments:
            return []

        chunks = []
        current_texts: list[str] = []
        window_start = segments[0].get("from", 0)

        for seg in segments:
            seg_start = seg.get("from", 0)
            seg_text = seg.get("content", "").strip()

            if not seg_text:
                continue

            # Start new window if we've exceeded the time threshold
            if seg_start - window_start >= window_seconds and current_texts:
                chunks.append(
                    RawContentChunk(
                        source_type=source_type,
                        raw_text="\n".join(current_texts),
                        metadata={
                            "start_time": window_start,
                            "end_time": seg_start,
                        },
                        media_url=f"https://www.bilibili.com/video/{bvid}",
                    )
                )
                current_texts = []
                window_start = seg_start

            current_texts.append(seg_text)

        # Flush remaining
        if current_texts:
            last_end = segments[-1].get("to", segments[-1].get("from", 0))
            chunks.append(
                RawContentChunk(
                    source_type=source_type,
                    raw_text="\n".join(current_texts),
                    metadata={
                        "start_time": window_start,
                        "end_time": last_end,
                    },
                    media_url=f"https://www.bilibili.com/video/{bvid}",
                )
            )

        return chunks
